# GitHub Action, die aus den LiaScript-Materialien des Sommersemester 2020 ein
# Skript generiert
name: GeneratePdf

# Hier legen wir den Trigger für die Action fest.
# "Wenn ein Push auf dem branch SoSe2020 realisert wird, werden die
# nachfolgenden Schritte ausgeführt"
on:
  push:
    branches:
      - SoSe2020

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    container: 
      image: docker://mirisbowring/texlive_ctan_full:2019
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2
        with:
          ref: SoSe2020
        # Ausführen des Parsers, der bestimmte Elemente im LiaCode entfernt
      - name: Run preprocessing
        run : |
          python3 .github/workflows/preprocessing.py
          mkdir output
        # Installation der notwendigen Pandoc tools
      - name: Install pandoc
        run: |
          sudo apt install pandoc
      # Generierungsprozess
      - name: Run pandoc markdown to tex
        run: |
          pandoc --toc --top-level-division=chapter -V linkcolor:blue --pdf-engine=xelatex --include-in-header=.github/workflows/header.tex -f markdown -t latex -o output/script.tex *.mdx
      - name: Run pandoc markdown to pdf
        run: |
          pandoc --toc --top-level-division=chapter -V linkcolor:blue --pdf-engine=xelatex --include-in-header=.github/workflows/header.tex -o output/script.pdf *.mdx
      # Speichern als Artifact
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
