name: GeneratePdf

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2
        with:
          ref: SoSe2020
      - name: Set environment variables
        run : |
          echo ::set-env name=FILELIST::$(ls *.md)
          mkdir output
      - name: Show variable
        run : |
          echo $FILELIST
      - name: Run Pandoc for all lecture files
        uses: docker://pandoc/latex:2.9
        with:
          args: --toc --top-level-division=chapter -V geometry:margin=2cm -V linkcolor:blue --pdf-engine=xelatex --output=output/script.pdf ${{ env.FILELIST }}
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
